### PR TITLE
Added simple links to the dropdown to address Issue #48.

### PR DESCRIPTION
**Pull request by ludagoo**
There is a more interesting way to do it with JS but it needs changes to http headers from the doors

### CODE REVIEW

**Comment by hef** [comment]
There should be way for these links to work A: only if the user is signed in, and B, even if they are not on the PS:One network.

**Comment by codersquid** [comment]
It looks like it is checking to make sure a user is signed in before showing the links.

Is it intentional for the backdoor link not to have a target?

**Comment by buildmon** [comment]
Can one of the admins verify this patch?

**Comment by hef** [comment]
ok to test

**Comment by hef** [comment]
this has been repalced by #112

**Pull request closed without merging**
