### PR TITLE
upgrade django reversion

### LINKED ISSUE #104: Trying to view a instance of a person history in the admin section causes a crash
First triggered by @dkoppel 

Generates a 

IDCheckInline' object has no attribute 'queryset'

attribute exception

### PR DESCRIPTION
**Pull request by hef**
fixes #104

### CODE REVIEW

**Comment by agocs** [comment]
Upping the django version fixed "If you try and view the change history in the admin section of a member management entry, the site would return a 500."? Would it be a pain in the butt to write a test around that?

**Comment by hef** [comment]
For clarification, I upped the [django-reversion](https://github.com/etianen/django-reversion) library is used as a way to version control certain django models.  It's not django itself.

I'll look at adding a test to load the view that was affected

**Comment by dkoppel** [comment]
I'm able to pull up history on people objects now, and pull up the previous revisions of objects. This appears to resolve #104

Interestingly enough, my test env struggles with pulling up people in the django admin interface.  I had to raise nginx and gunicorn timeouts to test this.  This is likely due to increased load running full prod data in my vagrant, however I thought I might note it here in case it comes up again, there may be some performance issues.

This request took 208s:
10.0.2.2 - - [12/Jul/2015:11:58:42 -0500] "GET /admin/member_management/person/827/ HTTP/1.1" 200 207526 "http://localhost:8001/admin/member_management/person/" "Mozilla/5.0 (X11; Fedora; Linux x86_64; rv:38.0) Gecko/20100101 Firefox/38.0"

**Comment by hef** [comment]
There are a few reasons prod data could be slow:  It could be building up cache data out of ldap, and not yet completed.  The other big culprit is trying to view someone with a lot of email records.  The django admin interface didn't appear sophisticated enough to fetch the metadata of email records without also fetching the content, even though the content is not displayed.  This is one of the reasons we stopped developing for the django admin interface and went back to regular custom views for most stuff.

**Comment by agocs** [comment]
Looks like a good change to me.

**Comment by hef** [comment]
approved by @agocs in irc

**Pull request merged**
